import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ProfileForm from "./ui/ProfileForm";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
         <div className="lg:flex"> 
          <div className="lg:m-7 lg:w-4/12 md:mx-4  sm:mx-4 hidden md:hidden lg:block "> <ProfileForm />   </div> 
          <div className="lg:my-7 lg:w-7/12 md:mx-4 sm:mx-4 "> {children}  </div>   
          
          
        </div>   
        {/* {profile}
        {mydetails} */}
      </body>
    </html>
  );
}
